version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    # volumes:
    #   - ./:/usr/src/app
    environment:
      - ENVIRONMENT=dev
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
    restart: always